### ISSUE TITLE
linux binaries 

### ISSUE THREAD

**Issue by shahto** [fordanic/openslide-matlab#11]
I used to run openslide-matlab on windows easily with using windows binaries from openslide.
I am working on to transfer the code on Linux OS and was unable to find/create binaries for Linux
I tried installing openslide from GitHub and facing multiple errors and think there are many dependencies to build it.
Is there an easy solution to run openslide- matlab in Linux environment?

**Comment by fordanic** [comment]
At the moment, I no longer have access to Matlab, so difficult for me to help troubleshoot. But it sounds to me that you issue is related to how to install/build openslide on Linux. Correct? If so, then your questions are better directed towards the openslide community.

**Comment by shahto** [comment]
Ok,Thanks for quick reply. So this code can be used in Linux but it depends on the installation process of Openslide package, which is not required in Windows. for windows all you need is binaries from openslide and it works.

**Comment by fordanic** [comment]
Yes, the code should be possible to use on Linux as well without any changes. The only thing needed is to install/build openslide and make sure that it is available on the Matlab path.

Closing the issue.
