### ISSUE TITLE
Error while loading library

### ISSUE THREAD

**Issue by shahto** [fordanic/openslide-matlab#12]
Openslide is installed and added to matlab path, yet I get this error

_**There was an error loading the library
"/home/product/openslide/3.4.1/centos76_x86_64/lib/libopenslide.so.0"
/lib64/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates

 Error using loaddefinedlibrary
    /lib64/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates**_

**Comment by fordanic** [comment]
My guess is that this is an issue for openslide being compiled with another version of libcairo compared to your installation. How did you install openslide?

**Comment by shahto** [comment]
Installed by someone with root access. I could not install myself.

**Comment by fordanic** [comment]
So, again, the issue is not with the MATLAB code but rather with openslide itself. Not something that can be handled here.
