### ISSUE TITLE
Error loading libraries

### ISSUE THREAD

**Issue by niraed** [fordanic/openslide-matlab#3]
Firstly, thank you for provide us openslide in matlab.
Secondly, I have a problem compiling my program (or some problems).
I'm using Matlab2015a and I get this from my .exe:

```
Error using loadlibrary (line 249)
Deployed applications must use a prototype file instead of a header file.  
To create the prototype, use the loadlibrary mfilename option.
 Use the prototype file in compiled code. 
 See http://www.mathworks.com/help/compiler/matlab-library-loading.html 
for more information.
```

Then, I try creating  prototype file :
`loadlibrary(libName, 'openslide-wrapper.h','alias','openslidelib','addheader','openslide.h',  'mfilename', 'openslideproto')`
and modify loadlibrary line in openslide_load_library:
`loadlibrary(libName, @openslideproto)`

Now, I get : 
`Warning: The library name is not a valid name. The library will be named "libopenslide0x2D0".`

So I change all libopenslide-0.dll names to libopenslide.dll, repeat and compile my program.
Then, I get:

```
[0x7FEE9D3AAA0] ANOMALY: meaningless REX prefix used
[0x7FEE9D248C0] ANOMALY: meaningless REX prefix used
Error using openslide_load_library (line 89)
Failure to load openslide library
```

I don't know what to do :( I'm driving crazy!

**Comment by fordanic** [comment]
First of, which OS are you running on? I assume win given that you refer to an .exe file.
Second, you are assumed to try to load a library, not an executable, that is a .dll on windows.

What if you download the windows binaries from http://openslide.org/download/, place the files in the bin folder and the include folder in the same folder which you add to the MATLAB path, revert any changes on the MATLAB files and run openslide_example()?

**Comment by niraed** [comment]
Sorry, my fault. 
Yes, I use Windows 7 and yes, I have the windows binaries inside of my compiled file. It works perfectly when I run my program from Matlab. All those problems happen when I compile it with the App compiler and I try to open the .exe

**Comment by fordanic** [comment]
Then I'm guessing that the issue is not related to the MATLAb files provided in this repo but rather the compilation of the app. Do you have minimal example I try with?

**Comment by niraed** [comment]
Yes, if you compile "openslide_example.m" as "main file" adding to "Files required for your application to run" all libraries and functions, you get in openslide_example.exe: 

http://oi65.tinypic.com/5yi5g5.jpg

Library never loads :( Almost, in my case.

**Comment by fordanic** [comment]
Please specify what you mean by compiling, what command are you using and what compiler.

**Comment by niraed** [comment]
I'm using the "app compiler"  from matlab. http://es.mathworks.com/products/compiler/apps.html

**Comment by fordanic** [comment]
Ok, here's what I did to solve the issue.
Rename `libopenslide-0.dll` to `libopenslide.dll` (for some reason it appears that when creating the prototype file, there's and issue with included "-" in the file name).
Run

``` matlab
libName = 'libopenslide.dll';
loadlibrary(libName,'openslide-wrapper.h','mfilename','myLibraryFile','addheader','openslide.h')
```

Assuming that `openslide-wrapper.h` has already been created as usual. Change the load line (line 76) in `openslide_load_library.m` to

``` matlab
loadlibrary(libName,@myLibraryFile,'alias','openslidelib');
```

Create your package to compile for `openslide_example` and make sure to include all dlls from openslide, the test image, `myLibraryFile.m` and all header files. Compile and run.

At least this made it for me.

**Comment by niraed** [comment]
Thank you so much for your help!! It works!!! (with my program too)  Again, thank you!! ^^

**Comment by gabybrur** [comment]
I have the same poblema and despite what do you recommend not fix the error could help me please

**Comment by fordanic** [comment]
What is the same problem that you're having? Loading of the libraries for compiled MATLAB apps or something else?

**Comment by gabybrur** [comment]
If what happens is that I have this code:

`inp = 'redchicosur_gates.INP';
if ~(libisloaded('swmm5'))
  loadlibrary('swmm5');
end
rpt_file = strrep(lower(inp), '.inp', '.rpt');
out_file = strrep(lower(inp), '.inp', '.out');
error = calllib('swmm5','swmm_open',inp, rpt_file, out_file);
if error ~= 0
  if (libisloaded('swmm5'))
    unloadlibrary swmm5;
  end
  throw(ERROR_MSG_PATH);
end`

and to compile it and make it executable I get the following error

Deployed applications must use a prototype file instead oof a header file. To create the prototype, use the loadlibrary mfilename option. Use the prototype file in compiled code. See http://mathworks.com/help/compiler/matlab-library-loading.html for more information. Error in example.m at line 5

and can not do to fix it

**Comment by fordanic** [comment]
I'm sorry but I don't understand how this is related to the openslide bridge for MATLAB that this repo is concerned with. Please shed some further light on this.

**Comment by gabybrur** [comment]
I thought it was the same mistake because doing executable I get the error message very similar to solve . But not if there is a possibility to help me solve my problem

**Comment by fordanic** [comment]
As indicated earlier, since this is not related to the MATLAB scripts in this repo or even the openslide library I suggest for you to head over to the MATLAB forum instead.
