### ISSUE TITLE
How can I extract patches from the original high-resolution image according to my predefined magnification times?

### ISSUE THREAD

**Issue by brisker** [fordanic/openslide-matlab#4]
I have several svs tissue slide images and I want to extract patches from it on a magnification time of 10X and 20X respectively. How can I achieve this by the openslide-matlab tools?  Thank you!

**Comment by fordanic** [comment]
Do you have a specific set of tiles/patches you want to read or do you want extract all tiles/patches from a slide but with a certain size in terms of number of pixels.

**Comment by brisker** [comment]
@fordanic   Thanks for reply! For example, suppose I have a whole tissue slide image (*svs ) file, and if   I open it with the Aperio tool "ImageScope" it looks llike this:
![image](https://cloud.githubusercontent.com/assets/13804492/16537695/5acafe22-403c-11e6-98f2-8c42f8e7065f.png)
It has different magnification times: 20X ,10X, 5X ,etc. What I want to do is to use the openslide tool to extract all patches with a certain size from the whole slide image *svs files at different magnification times, according to my predefined parameters. Could you please tell me how to achieve this?

**Comment by fordanic** [comment]
Try:

``` matlab
% Parameters
tileSize = 512;
magnification = 20;

% Get folder of openslide_example
[folder,~,~] = fileparts(which('openslide_example'));

% Load openslide library
openslide_load_library();

% Set file name of whole-slide image to work with
WSI = [folder,filesep,'test_data',filesep,'CMU-1-Small-Region.svs'];

% Open whole-slide image
slidePtr = openslide_open(WSI);

% Get whole-slide image properties
[mppX, mppY, width, height, numberOfLevels, ...
    downsampleFactors, objectivePower] = openslide_get_slide_properties(slidePtr);

% Determine which level corresponds to desired magnification/objectivePower
levelToUse = find(objectivePower == magnification,1) - 1;

% Adjust image width and height accordingly
width = round(width / downsampleFactors(levelToUse + 1));
height = round(height / downsampleFactors(levelToUse + 1));

% Read all tiles
for colInd = 0 : floor(width/tileSize)
    for rowInd = 0 : floor(width/tileSize)
        % Set start indices and size
        startX = colInd * tileSize;
        startY = rowInd * tileSize;
        widthX = min(tileSize,tileSize - ((colInd + 1) * tileSize - width));
        heightY = min(tileSize,tileSize - ((rowInd + 1) * tileSize - height));

        % Read the tile
        ARGB = openslide_read_region(slidePtr,...
                                     startX,startY,widthX,heightY,...
                                     levelToUse);

        % Display RGB part
        figure(1)
        imshow(ARGB(:,:,2:4))
    end
end

% Close whole-slide image, note that the slidePtr must be removed manually
openslide_close(slidePtr)
clear slidePtr

% Unload library
openslide_unload_library
```

**Comment by brisker** [comment]
@fordanic    Thanks a lot! I will try it later!

**Comment by brisker** [comment]
@fordanic   Hello, I run the code and it went well. But when I replace the *svs file with my own, the code got bugs in this line: width = round(width / downsampleFactors(levelToUse + 1));
and in the variable window the levelTouse is null:
![image](https://cloud.githubusercontent.com/assets/13804492/16864040/b5421526-4a8b-11e6-83ec-9bb80e204816.png)
and in the command windows, it read: "error using / ,please use  RDIVIDE (./)"
I tried to change the magnification variable from 20 to 40 and the code went well again, but sometimes I need the magnification to be 20 or 5. How to fix the potential bug when the magnification is not the max level? Thank you!

**Comment by fordanic** [comment]
Try replacing the line where `levelToUse` is set with

``` matlab
levelToUse = find(objectivePower./round(downsampleFactors) == magnification,1) - 1;
```

**Comment by brisker** [comment]
@fordanic   Thanks a lot! And if I want to perform some algorithms on the patches but after that I want to visualize the result in a whole-slide-image-level way, do you think it is possible by using openslide?(I mean if it is possible to use openslide for generate a new *svs file after I perform the patch-level processing? Or maybe visualize the result not only in the patch-level)

**Comment by fordanic** [comment]
As far as I'm aware the openslide library does not support write operations but only read. If you want visualize the results on a whole-slide level I'd recommend to stitch the results together, after a suitable downsampling and then visualize it.
