### ISSUE TITLE
Error linking libraries #3

### ISSUE THREAD

**Issue by zarabozdag** [fordanic/openslide-matlab#6]
first of all thanks for codes,
I have problem when  i try the load library. I follow your instructions but getting errors. I use Windows 10 and Matlab R2012a

 >>openslide_example
Warning: Message from C preprocessor:
lcc preprocessor error:
C:\Users\bzdg\Desktop\my_OpenSlide\openslide-3.4.1\src\openslide-features.h:41
C:\Users\bzdg\Desktop\my_OpenSlide\openslide-3.4.1\src\openslide.h:33
C:\Users\bzdg\Desktop\my_OpenSlide\fordanic-openslide-matlab-976ac90\openslide-wrapper.h:4
Could not find include file <stdbool.h>
lcc preprocessor error:
C:\Users\bzdg\Desktop\my_OpenSlide\openslide-3.4.1\src\openslide.h:35
C:\Users\bzdg\Desktop\my_OpenSlide\fordanic-openslide-matlab-976ac90\openslide-wrapper.h:4
Could not find include file <stdint.h>
 
> In loadlibrary at 318
  In openslide_load_library at 76
  In openslide_example at 24 
Warning: Warnings messages were produced while parsing.  Check the functions you
intend to use for correctness.  Warning text can be viewed using:
 [notfound,warnings]=loadlibrary(...) 
> In loadlibrary at 344
  In openslide_load_library at 76
  In openslide_example at 24 
Error using loadlibrary (line 419)
There was an error loading the library
"C:\Users\bzdg\Desktop\my_OpenSlide\openslide-3.4.1\src\openslide-decode-tiff.c"
C:\Users\bzdg\Desktop\my_OpenSlide\openslide-3.4.1\src\openslide-decode-tiff.c
It is not a valid Win32 application.

Error in openslide_load_library (line 76)
loadlibrary(libName,'openslide-wrapper.h','alias','openslidelib',...

Error in openslide_example (line 24)
openslide_load_library();

Caused by:
    Error using loaddefinedlibrary
    C:\Users\bzdg\Desktop\my_OpenSlide\openslide-3.4.1\src\openslide-decode-tiff.c
    It is not a valid Win32 application.

----
in my laptop ,I use windows 10 and matlab R2015a version, I got following errors. 
  
>> openslide_example
Index exceeds matrix dimensions.

Error in loadlibrary>getLoadlibraryCompilerConfiguration (line 527)
Error in loadlibrary (line 263)
Error in openslide_load_library (line 76)
loadlibrary(libName,'openslide-wrapper.h','alias','openslidelib',...

Error in openslide_example (line 24)
openslide_load_library();

**Comment by fordanic** [comment]
Your first error seem to be caused that MATLAB cannot locate the appropriate binaries, and instead only finds source files. Note that you need to compile the Openslide library or download binaries directly.

Your second error doesn't make any sense to me. Could please include the complete error message provided when running openslide_example.

Thanks

**Comment by fordanic** [comment]
Please provide further feedback or else I'll close this issue given that there is not enough information available for me to investigate further.

Thanks

**Comment by zarabozdag** [comment]
thanks a lot, It is  my fault, It is solved.
have a nice day.
