### ISSUE TITLE
Error loading openslide library

### ISSUE THREAD

**Issue by Suvi-dha** [fordanic/openslide-matlab#8]
Hi, after trying so many times, I am still getting this error 

```
Error in openslide_load_library (line 76)
loadlibrary(libName,'openslide-wrapper.h','alias','openslidelib',...

Caused by:
    Error using loaddefinedlibrary
    The specified procedure could not be found.
```

What could I be doing wrong?

**Comment by fordanic** [comment]
Would care to explain in more detail what you have prior to receiving this error message?

**Comment by Suvi-dha** [comment]
ok, so  I am trying to run openslide_example.m. I have copied all the .dll files and .h files in my matlab path. I tried to debug this particular error, but it is really a long chain of functions. I am just getting this above reported error and no trace back information. I don't know what else to tell you. 
I guess, I will try again today debugging the error and then if I find something, will get back to you.

**Comment by Suvi-dha** [comment]
I got it working, thanks. :)
